codecov:
    require_ci_to_pass: false

coverage:
    precision: 2
    round: nearest
    status:
        project:
            default:
                target: auto
                threshold: 1%
                base: auto
        patch:
            default:
                target: auto
                threshold: 1%

ignore:
  - "tests/*"
  - "dev/*"
